// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQpUjMGjCBaUON50VcQ6bmZWX3FL9Mc0',
    appId: '1:136930695034:web:d968795067e6f085d7e8c3',
    messagingSenderId: '136930695034',
    projectId: 'final-hackathon-7a3c2',
    authDomain: 'final-hackathon-7a3c2.firebaseapp.com',
    storageBucket: 'final-hackathon-7a3c2.appspot.com',
    measurementId: 'G-E0K0LPQWWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuPqkexdI5zZ7kbO90yZ4fM5t8nOdHimY',
    appId: '1:136930695034:android:88046e8c7237f12cd7e8c3',
    messagingSenderId: '136930695034',
    projectId: 'final-hackathon-7a3c2',
    storageBucket: 'final-hackathon-7a3c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-VhYyVUr6LNiAjaUlI7L-jStawA95MM',
    appId: '1:136930695034:ios:8861f3821b7854bdd7e8c3',
    messagingSenderId: '136930695034',
    projectId: 'final-hackathon-7a3c2',
    storageBucket: 'final-hackathon-7a3c2.appspot.com',
    iosBundleId: 'com.example.hackhthonProject',
  );
}
